spring.application.name=proyectoPaleteria
# PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://neondb_owner:npg_bsmxWe8Y2AIr@ep-bold-base-apmx47vn-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=lizettehuerta63@gmail.com
spring.datasource.password=Lizet123_a
spring.jpa.hibernate.ddl-auto=update

# MongoDB (Atlas)
spring.data.mongodb.uri=mongodb+srv://lizettehuerta63_db_user:lizet123_a@proyectopaleteria.vjbezjy.mongodb.net/?appName=proyectoPaleteria
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
